# TODO: build (test) on each push, deploy on push to master

name: ci
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 # needed to use the local action
      - name: build
        uses: ./.github/actions/mkdocs # a local action
        with:
          command: "mkdocs build"

  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 # needed to use the local action
      - name: deploy
        uses: ./.github/actions/mkdocs # a local action
        with:
          command: "mkdocs gh-deploy --force"
